name: CI

on: [push, pull_request]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig build -Dtarget=aarch64-linux-musl
      - run: zig build -Dtarget=x86_64-linux-musl
      - run: zig build -Dtarget=aarch64-linux-gnu
      - run: zig build -Dtarget=x86_64-linux-gnu

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check *.zig build.zig.zon
